Added unit tests
MO-Movia/licit-plugin-contrib-paste-json pull request #10
Opened 2023-05-24 08:43 UTC by visakh-ms

2023-05-25 14:12 UTC, rodgersgb approved these changes

2023-05-25 14:18 UTC, Tezra requested changes
Only 2 lines away from complete coverage. Can you please add 2 more tests to cover lines 59 and 76?

2023-05-26 11:03 UTC, visakh-ms commented
I have added 2 unit tests. Now the coverage is 100%.

2023-05-26 11:18 UTC, Tezra approved these changes

2023-05-26 11:18 UTC, Tezra approved these changes

2023-05-30 12:54 UTC, merged